### ISSUE TITLE
Fix map dimensions

### ISSUE THREAD

**Issue by jennygrahamjones** [jennygrahamjones/galaxy-map#12]
The upper and lower most grid squares (the Outer Rim and Wild Space sectors of the map) are compressed as a result of the map being rectangular, rather than a square ([ref](https://vignette.wikia.nocookie.net/starwars/images/6/66/The_Galaxy_-_TROS_Visual_Dictionary.png/revision/latest?cb=20200102070639)).

**Comment by cacasale** [comment]
Do we know what the distortion rate is? I can adjust it accordingly.

**Comment by jennygrahamjones** [comment]
It looks like leaflet defaults to what is apparently an '[Mercator projection](https://en.wikipedia.org/wiki/Web_Mercator_projection)' for the map's dimensions. There are apparently packages (e.g. [Proj4Leaflet](https://kartena.github.io/Proj4Leaflet/)) you can use to define your own map projection, but (quoting Proj4Leaflet)...

>Tiling in projections other than spherical mercator (the projection used in Leaflet by default) is a complex topic

😬I'm not sure there is a CSS fix, sadly. Happy to be proven wrong, though!
